# Generated by Django 5.0 on 2024-02-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
